version: '3.9'
services:
  db:
    build: .
    container_name: almacenes_db
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./queries.sql:/queries.sql
      